# https://raw.githubusercontent.com/hbstack/site/main/config/_default/menus.en.yml

main:
  - name: Universal
    identifier: pseudocode
    weight: 1
    params:
      icon:
        vendor: bs
        name: book
  - name: Language Specific
    identifier: docs
    weight: 2
    params:
      icon:
        vendor: bs
        name: book
  - name: Specialty
    identifier: specialty
    weight: 3
    params:
      icon:
        vendor: bs
        name: book

  - name: Tags
    identifier: patterns
    weight: 1000
    params:
      icon:
        name: boxes
        #color: 'skyblue'
        className: text-primary