title_separator: '|'
title_sections: true # when false, remove the sections from the title.
title_sections_depth: 4 # the depth of sections on the title.
title_sections_depth_dir: start # when start, the depth is counting from the root sections.

description: >
  Dive into real-life examples across a multitude of languages including C#, Clojure, C++, D, Dart, Elixir, 
  F#, Go, Haskell, Haxe, Java, JavaScript, Julia, Kotlin, Lua, PHP, Python, Ruby, Scala, SQL, Swift, TypeScript, and more. 
  Discover the benefits and trade-offs, and learn how to harness language-specific features and paradigms. 
  Test your understanding with engaging quizzes, enhancing your learning experience and reinforcing key concepts. Enhance your coding skills and tackle complex challenges with confidence using proven solutions from the world of software development.
code_block_panel:
  max_lines: 125


meta: 
  date: false
  reading_time: true
  
hb:
  # override SASS variables, please replace the dash with underline, e.g. `list-group-color` should be `list_group_color`.
  styles:
    # https://imagecolorpicker.com/color-code/094e15
    primary: '#0004FF'
  

  full_width: false
  revision:
    repo_service: github
    repo_owner: MasteryEducation
    repo_name: SoftwarePatternsLexicon.com
    repo_branch: main
    repo_subpath: ''
    repo_contributors: true
    repo_actions: true
    icons: true
    created_at: false
    date_format: ':date_full'
    font_size: '.825rem'
  header:
    brand: Design Patterns
    socials:
      # github: hbstack
      # twitter: razonyang
      # rss: true
      # mastodon: https://techhub.social/@hbstack
  footer:
    powered_by: true
    # see https://hbstack.dev/en/docs/modules/socials/.
    socials:
  terms:
    paginate: 100
  blog:
    sidebar:
      profile:
        title: Design Patterns
      posts:
        recent_count: 0
        featured_count: 0
        recent_posts: 0
        list_style: vertical
      taxonomies:
        count: true
        limit: 1000
        separate: false
        style: pills
        authors:
         title: Authors
         disable: false
         limit: 100
         weight: 4
        categories:
          disable: false
          weight: 1
          title: Categories
          limit: 1000
        series:
          disable: false
          limit: 100
          title: Series
          weight: 2
        tags:
          disable: false
          limit: 1000
          title: Tags
          weight: 3
    paginate: 4
    post_thumbnail_height: 4
    post_thumbnail: false
    related_posts:
      list_style: vertical
    home:
      taxonomies: false
      featured_posts: 0
      main_sections:
        - patterns-java
    #giscus:
      #repo: hbstack/theme
      #repo_id: R_kgDOJP3qtA
      #category_id: DIC_kwDOJP3qtM4CVavM
  docs:
    #https://hugomods.com/docs/comment-engines/giscus/
    giscus:
      repo: MasteryEducation/SoftwarePatternsLexicon.com
      repo_id: R_kgDOMP0ZOw
      category: Announcements
      category_id: DIC_kwDOMP0ZO84CkWlH
      mapping: title
      strict_matching: true
      input_position: top
      reactions: true
      lazy_loading: false



  # https://hbstack.dev/modules/components/content-panel/
  content_panel:
    comments: false

seo:
  # https://hugomods.com/en/docs/seo/#favicons-module
  favicons: 
    icon: images/logo.png # use logo as favicon.

# https://hugomods.com/en/docs/pwa/#site-parameters
pwa:
  debug: false
  manifest:
    background_color: '#712cf9'
    theme_color: '#712cf9'
    short_name: 'Design Patterns'

# https://hugomods.com/search/configurations/
search:
  #distance: 25
  #ignore_location: false
  #location: 0
  #threshold: 0.8
  #stall_threshold: 300
  #min_match_char_length: 50 # so that smaller subtitles should not match
  #case_sensitive: false
  # shortcut_search: ["/"]
  #key_weights.title: 1000
  #key_weights.headings: 0.001
  #key_weights.summary: 0.001
  #key_weights.content: 0
  index_content: false
  #expand_results_meta: true
  filter_taxonomies: false
  filter_years: false
  headings_end_level: 1
  index_headings: false
  index_summary: false
  index_taxonomies: false

mermaid:
  js_url: https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs

hugopress:
  modules:
    hb-custom:
      hooks:
        # see layouts/partials/hugopress/modules/hb-custom/hooks/head-end.html.
        head-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/body-end.html.
        body-end:
          cacheable: true
        hb-footer-end:
          cacheable: true
        # see layouts/partials/hugopress/modules/hb-custom/hooks/hb-blog-sidebar.html.
        hb-blog-sidebar:
          cacheable: true
          weight: 1
    # change the order of sidebar modules.
    hb-blog-sidebar-taxonomies:
      hooks:
        hb-blog-sidebar:
          weight: 3
    hb-blog-sidebar-posts:
      hooks:
        hb-blog-sidebar:
          weight: 2
